# apiVersion: v1
# kind: Service
# metadata:
#   name: service #The name of the Kubernetes Service to be created in the Kubernetes cluster
# spec:
#   selector:
#     app: react-app 
#   type: LoadBalancer 
#   ports:
#   - protocol: TCP
#     port: 8080 
#     targetPort: 80 

apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    app: react-app
