apiVersion: v1
kind: Service
metadata:
  name: service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: react-app 
  type: LoadBalancer 
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: 80 
